# Generated by Django 6.0.3 on 2026-03-21 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('slack', 'Slack'), ('notion', 'Notion')], max_length=50)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('expired', 'Expired'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='IntegrationPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('is_granted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'integration_permissions',
            },
        ),
    ]
